# Generated by Django 6.0.5 on 2026-06-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Optional instructions or context shown to the student before they begin.', null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time the attempt was submitted.'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Score as a percentage: (score / total_questions) × 100.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total number of questions in the quiz at the time of this attempt.'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(help_text='The choice (option) the student selected.', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assessments.choice'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Snapshot of whether this choice was correct at submission time. Stored to preserve result history even if the question is later edited.'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
    ]
