"""
assessments/admin.py

Registers all Phase 3 models with the Django admin site.

Design decisions
----------------
- ChoiceInline is nested inside QuestionInline so a teacher can build an
  entire quiz (questions + choices) from a single admin page.
- QuestionInline is nested inside QuizAdmin for the same reason.
- QuizAttempt and StudentAnswer are read-only in the admin — they are
  generated by student submissions and should never be manually edited.
  All editable fields are removed; list_display gives full visibility.
- StudentAnswerInline is nested inside QuizAttemptAdmin so admins can
  review exactly what a student submitted without navigating away.
"""

from django.contrib import admin
from .models import Quiz, Question, Choice, QuizAttempt, StudentAnswer


# ─────────────────────────────────────────────────────────────────────────────
# Inlines
# ─────────────────────────────────────────────────────────────────────────────

class ChoiceInline(admin.TabularInline):
    """
    Choices shown inline inside the Question change page.
    Teachers can add/edit all answer options for a question in one place.
    """
    model = Choice
    extra = 4          # Show 4 blank rows by default — typical MCQ has 4 options
    fields = ('choice_text', 'is_correct')
    verbose_name = 'Answer Choice'
    verbose_name_plural = 'Answer Choices'


class QuestionInline(admin.StackedInline):
    """
    Questions shown inline inside the Quiz change page.
    StackedInline (rather than Tabular) gives more vertical space for
    question_text, which can be long.
    """
    model = Question
    extra = 1
    fields = ('order', 'question_text')
    ordering = ('order',)
    show_change_link = True   # Link to the full Question page where ChoiceInline lives
    verbose_name = 'Question'
    verbose_name_plural = 'Questions'


class StudentAnswerInline(admin.TabularInline):
    """
    Student answers shown inline inside a QuizAttempt.
    Read-only — admins can review but not alter submitted answers.
    """
    model = StudentAnswer
    extra = 0
    readonly_fields = ('question', 'choice', 'is_correct')
    can_delete = False
    verbose_name = 'Answer'
    verbose_name_plural = 'Submitted Answers'

    def has_add_permission(self, request, obj=None):
        return False


# ─────────────────────────────────────────────────────────────────────────────
# Quiz
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(Quiz)
class QuizAdmin(admin.ModelAdmin):
    list_display  = ('title', 'course', 'passing_score', 'question_count', 'created_at')
    list_filter   = ('course', 'passing_score')
    search_fields = ('title', 'course__title')
    ordering      = ('course', 'created_at')
    inlines       = [QuestionInline]

    fieldsets = (
        (None, {
            'fields': ('course', 'title', 'description'),
        }),
        ('Pass / Fail Threshold', {
            'fields': ('passing_score',),
            'description': 'Students must reach this percentage (0–100) to pass.',
        }),
    )


# ─────────────────────────────────────────────────────────────────────────────
# Question
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(Question)
class QuestionAdmin(admin.ModelAdmin):
    list_display  = ('__str__', 'quiz', 'order')
    list_filter   = ('quiz',)
    search_fields = ('question_text', 'quiz__title')
    ordering      = ('quiz', 'order')
    inlines       = [ChoiceInline]

    fieldsets = (
        (None, {
            'fields': ('quiz', 'order', 'question_text'),
        }),
    )


# ─────────────────────────────────────────────────────────────────────────────
# Choice
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(Choice)
class ChoiceAdmin(admin.ModelAdmin):
    list_display  = ('choice_text', 'question', 'is_correct')
    list_filter   = ('is_correct', 'question__quiz')
    search_fields = ('choice_text', 'question__question_text')
    ordering      = ('question',)


# ─────────────────────────────────────────────────────────────────────────────
# QuizAttempt  (read-only)
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(QuizAttempt)
class QuizAttemptAdmin(admin.ModelAdmin):
    list_display   = ('student', 'quiz', 'score', 'total_questions', 'percentage', 'passed', 'created_at')
    list_filter    = ('passed', 'quiz', 'quiz__course')
    search_fields  = ('student__username', 'student__email', 'quiz__title')
    ordering       = ('-created_at',)
    readonly_fields = (
        'student', 'quiz', 'score', 'total_questions',
        'percentage', 'passed', 'created_at',
    )
    inlines        = [StudentAnswerInline]

    # Prevent creating attempts manually from the admin
    def has_add_permission(self, request):
        return False

    fieldsets = (
        ('Attempt Details', {
            'fields': ('student', 'quiz', 'created_at'),
        }),
        ('Result', {
            'fields': ('score', 'total_questions', 'percentage', 'passed'),
        }),
    )


# ─────────────────────────────────────────────────────────────────────────────
# StudentAnswer  (read-only)
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(StudentAnswer)
class StudentAnswerAdmin(admin.ModelAdmin):
    list_display   = ('__str__', 'attempt', 'is_correct')
    list_filter    = ('is_correct', 'attempt__quiz')
    search_fields  = ('attempt__student__username', 'question__question_text')
    ordering       = ('attempt', 'question__order')
    readonly_fields = ('attempt', 'question', 'choice', 'is_correct')

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False
