# Generated by Django 6.0.5 on 2026-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the student last marked this lesson complete. Null if incomplete.', null=True),
        ),
    ]
