# Generated by Django 6.0.5 on 2026-06-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lessonprogress_completed_at'),
        ('courses', '0004_coursecertificate'),
    ]

    operations = [
    ]
